spring:
  #  thymelaef 配置
  thymeleaf:
    cache: false

  #redis 配置
  redis:
  #服务器地址
    host: 192.168.152.130
    port: 6379
    #数据库
    database: 0
    #超时时间
    timeout: 10000ms
    lettuce:
      pool:
      #最大连接数
        max-active : 8
        #最大连接阻塞等待时间，默认-1
        max-wait: 10000ms
        #最大空闲连接，默认8
        max-idle: 200
        #最小空闲连接，默认0
        min-idle: 5


  # 数据源配置
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.152.130:3306/sec_kill_sys?useUnicode=true&useSSL=false&characterEncoding=utf8
    username: root
    password: xxxxxxx
    hikari:
      #连接池名
      pool-name: DateHikariCP
      #最小空闲连接数
      minimum-idle: 5
      #空闲连接存活最大时间，默认600000（10min）
      idle-timeout: 180000
      #最大连接数 默认10
      maximum-pool-size: 10
      #从连接池返回的连接自动提交
      auto-commit: true
      #连接最大存活时间，0表示永久存活，默认1800000（30分钟）
      max-lifetime: 1800000
      #连接超时时间，默认30000（30秒）
      connection-timeout: 180000
      #测试连接是否可用的查询语句
      connection-test-query: SELECT 1
  web:
    #静态资源处理
    resources:
      cache:
        cachecontrol:
          #cache超时时间
          max-age: 3600
      chain:
        cache: true
        enabled: true
        compressed: true

  rabbitmq:
    host: 192.168.152.130
    username: guest
    password: guest
    virtual-host: /
    port: 5672
    listener:
      simple:
        #消费者最小数量
        concurrency: 10
        #消费者最大数量
        max-concurrency: 10
        #限制消费者每次只处理一条消息，处理完再继续下一条消息
        perfetch: 1
        #启动时是否默认启动器，默认true
        auto-startup: true
        #被拒绝时重新进入队列
        default-requeue-rejected: true
    template:
      retry:
        #发布重试，默认false
        enabled: true
        #重试时间，默认1000ms
        initial-interval: 1000ms
        #重试最大次数
        max-attenpts: 3
        #重试最大间隔时间，默认10000ms
        max-interval: 10000ms
        #重试的间隔乘数。如果配2.0 则第一次就等10s 第二次等20s 第三次等40s
        multiplier: 1



#Mybatis-plus配置
mybatis-plus:
  # 配置Mapper.xml映射文件
  mapper-locations: classpath*:/mapper/*Mapper.xml
  # 配置MyBatis数据返回类型别名（默认别名是类名）
  type-aliases-package: tech.snnukf.seckillsys.pojo

# MyBatis SQL打印（方法接口所在的包，不是Mapper.xml所在的包）
logging:
  level:
    tech.snnukf.seckill.mapper: debug
